import pandas as pd 
df=pd.DataFrame( pd.read_csv("F:/python/Pandas/raw_data.csv"))
print(df["name"].str.split(" "))
print(df["name"].str.upper()) #similaly lower will work
print(df["name"].str.strip())
print(df["name"].str.contains("john doe", case=False))
"""".str.lower()
.str.upper()
.str.title()
.str.strip()
.str.len()
.str.contains()
.str.startswith()
.str.endswith()
.str.find()
.str.replace()
.str.split()
.str.rsplit()
.str.join()
.str.get()
.str.slice()
.str.extract()
.str.extractall()
.str.findall()
.str.match()
.str.fullmatch()
.str.count()
.str.pad()
.str.zfill()
.str.cat()
.str.isalnum()
.str.isalpha()
.str.isdigit()
.str.isspace()"""